name: Build and Deploy to Staging

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Build node js project
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run
